### ISSUE TITLE
Create smartmon exporter repository

### ISSUE THREAD

**Issue by pgier** [prometheus-community/community#3]
I'd like to start a new prometheus community project for exporting SMART metrics.  I've created some prototype code in my personal repository (https://github.com/pgier/smartmon-exporter).  There seems to be some demand for smart metrics to be added to node_exporter (https://github.com/prometheus/node_exporter/issues/473, https://github.com/prometheus/node_exporter/issues/782), but due to some of the constraints of node_exporter (no root priveledges, using external binaries, etc) it might make more sense for this to be a separate exporter.

**Comment by SuperQ** [comment]
Sounds like a good one to me. I am willing to sponsor this project.

**Comment by kfox1111** [comment]
Any movement on this?

**Comment by SuperQ** [comment]
@pgier If you can grant me admin access to your repo, I can move it over.

**Comment by pgier** [comment]
No, I haven't worked on it at all.  Feel free to fork my repo, or start a new one or whatever.  If it's helpful, I can give @SuperQ admin access to the repo.

**Comment by frittentheke** [comment]
... currently people looking for monitoring of disk health or smartmon data are pointed to two scripts (one Python the other bash) producing metrics to be handled by the textfile exporter:
* https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/master/smartmon.sh
* https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/master/smartmon.py

and there definitely is interest in having smartmon data (see: https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/issues?q=smartmon). But since there always are calls to an external binary involved, I doubt it will ever end up as a collector within the node_exporter itself, or am I mistaken @SuperQ ?

Question then is if a standalone exporter like yours @pgier, written in Golang and therefore lightweight and with no real dependencies on the system, or further improvements to the Python script (i.e. https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/pull/67#issuecomment-760892826) are the way forward.

In any case, just adding yet another implementation to me is not helping to gain traction on stability on features for this data to be available and scrapeable by Prometheus.

**Comment by kfox1111** [comment]
https://github.com/Sheridan/smartctl_exporter is another option. I've had fairly good luck with it.

Big +1 for some kind of community supported smart data exporter though, whatever the route.

**Comment by SuperQ** [comment]
@frittentheke Without a way to get the data via some kernel interface, it's not likely to be in the node_exporter.

The smartctl_exporter looks like probably the best option. If the owners want to move it to prometheus-community, I'd be happy to help with that.

**Comment by kfox1111** [comment]
The author of https://github.com/Sheridan/smartctl_exporter would be willing to contribute the exporter. What do we need to do to get him a repo under prometheus-community? Anyone here that can assist him through the process? I've never done it before.

**Comment by kfox1111** [comment]
So, how do we find a Prometheus-Team member?

Who has the ability to create the GitHub team?

**Comment by SuperQ** [comment]
I've created the team and invited @Sheridan.

**Comment by k0ste** [comment]
@SuperQ, I contacted with @Sheridan directly, and we find out that he can't add, for example @NiceGuyIT or @vagifzeynalov, to repo members. I think this guys can warm up this repo with patches, so somebody need merge permissions. The original author of exporter too busy to review new code

Thanks!

**Comment by Sheridan** [comment]
I am have no acces to access setings
![image](https://user-images.githubusercontent.com/728591/154482139-6af72f8d-97e4-4f6a-b031-1c84761aa936.png)

**Comment by NiceGuyIT** [comment]
Any movement on this front? There are 9 PRs outstanding and some (myself included) have forked the repo just to be able to merge the PRs that affect them.

**Comment by SuperQ** [comment]
This has been moved, but we need more people to review PRs.

**Comment by bjornfor** [comment]
If this issue is resolved, where is the new smartmon exporter repo?

**Comment by SuperQ** [comment]
https://github.com/prometheus-community/smartctl_exporter

**Comment by bjornfor** [comment]
> https://github.com/prometheus-community/smartctl_exporter

So that's what users should use now instead of https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/master/smartmon.py?
